### ISSUE TITLE
Drag'n'Drop Support

### ISSUE THREAD

**Issue by a-elkaim** [FallingSnow/h265ize-gui#7]
Currently drag'n'droping a file open some kind of web player instead of adding the files to the queue, would it possible to drag'n'drop folders / files ?

**Comment by FallingSnow** [comment]
I actually thought of this earlier and looked into it. It seems a little complex so I put it off for now, but it definitely will be a feature in the future, I just have to take the time to add it.

**Comment by a-elkaim** [comment]
By the way, is there a reason you went with node.js instead of going for something such as the very effective C++ / Qt combo ?

**Comment by FallingSnow** [comment]
I actually have a lot of reasons lol.

*I'm going to school for comp sci right now so I'm only learning C++ now where as I know JavaScript fairly well already.
*I'm under the impression that a C++/Qt combo has a longer development cycle.
*This isn't a performance intensive app (probably the farthest thing from it) so I don't need C++ performance.

**Comment by FallingSnow** [comment]
I was working on drag and drop support last night so that will be coming soon.

**Comment by a-elkaim** [comment]
Sure, but it requires the user to install node.js instead of having a standalone application.

If you allow me, I might fork the project and try to reproduce it with a C++ / Qt combo.

**Comment by FallingSnow** [comment]
The builds will not require you to install node.js. It will be a bundled exe using nwjs.

Sure. You are free to whatever you please. :)
