### ISSUE TITLE
[Bug] Mkv not recognized as valid video files

### ISSUE THREAD

**Issue by a-elkaim** [FallingSnow/h265ize-gui#8]
Under windows, I launched the GUI, added a mkv file, got the error : filename.mkv is not a valid video file.

I couldn't find any logs anywhere.

**Comment by FallingSnow** [comment]
This means that ffprobe, the scanning mechanism for ffmpeg, was not able to scan the video. You can find the exact error if you go to the log tab, click the floating action button in the bottom right, and change the log level to debug.

**Comment by a-elkaim** [comment]
`warn awesome_movie.mkv could not be added because of an ffprobe processing error.`

Isn't ffprobe a dependency of the project ?

**Comment by FallingSnow** [comment]
A dependency that you must install, yes.

Can you upload these videos for me to test?

**Comment by azsde** [comment]
Aha, I thought npm installed ffprobe for me, i need to install it on windows and then I'll try again.

**Comment by a-elkaim** [comment]
ffprobe is installed under C:\ffmpeg\bin tho, so I don't know why it would not be recognized.

**Comment by FallingSnow** [comment]
Is it in your path?

**Comment by a-elkaim** [comment]
Yes it is in my path

**Comment by FallingSnow** [comment]
Does the log page have an errors?

**Comment by FallingSnow** [comment]
Make sure you toggle the log page's filter to debug.

**Comment by a-elkaim** [comment]
> debug ffprobe error:

It is empty, no more details :(

**Comment by FallingSnow** [comment]
Damn. This is probably bad coding on my part. There definitely should be an error there. Let me do some updates to the error system and push an update today. Then I'll tell you to try again.

**Comment by FallingSnow** [comment]
@azsde Thanks for being so patient. If you could retest you will find the log should be a lot more informative of the error. If you don't know what it means or it still doesn't appear to display an error, please let me know.

**Comment by FallingSnow** [comment]
Also, please do a complete reinstall. (delete the old directory and rerun the commands in the readme)
